const loginCard=document.querySelector("#login-card"),dashboard=document.querySelector("#dashboard"),loginForm=document.querySelector("#login-form"),loginStatus=document.querySelector("#login-status"),logout=document.querySelector("#logout"),passwordInput=document.querySelector("#password"),togglePassword=document.querySelector("#toggle-password");
async function api(url,options={}){const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Erreur");return d}
function showDashboard(){loginCard.hidden=true;dashboard.hidden=false;logout.hidden=false;loadKnowledge()}
async function check(){try{await api("/api/admin/session");showDashboard()}catch{}}
loginForm?.addEventListener("submit",async e=>{e.preventDefault();const b=loginForm.querySelector("button[type=submit]");loginStatus.textContent="Vérification…";b.disabled=true;try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:passwordInput.value})});loginForm.reset();showDashboard()}catch(x){loginStatus.textContent=x.message;loginStatus.className="form-status error"}finally{b.disabled=false}});
togglePassword?.addEventListener("click",()=>{const v=passwordInput.type==="text";passwordInput.type=v?"password":"text";togglePassword.textContent=v?"Afficher":"Masquer"});
logout?.addEventListener("click",async()=>{await api("/api/admin/logout",{method:"POST"}).catch(()=>{});location.reload()});
document.querySelectorAll(".admin-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".admin-section").forEach(x=>x.hidden=x.id!==b.dataset.tab);if(b.dataset.tab==="contacts")loadContacts()}));
document.querySelector("#knowledge-form")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f).entries());b.published=f.published.checked;try{await api("/api/admin/knowledge",{method:"POST",body:JSON.stringify(b)});f.reset();f.published.checked=true;document.querySelector("#knowledge-status").textContent="Réponse ajoutée.";loadKnowledge()}catch(x){document.querySelector("#knowledge-status").textContent=x.message}});
async function loadKnowledge(){const l=document.querySelector("#knowledge-list");try{const rows=await api("/api/admin/knowledge");l.innerHTML=rows.map(x=>`<article class="admin-item"><div><span class="ticket-status ${x.published?"answered":"closed"}">${x.published?"Active":"Désactivée"}</span><h3>${esc(x.title)}</h3><small>${esc(x.category||"Général")}</small><p>${esc(x.content)}</p></div></article>`).join("")||'<div class="empty-state">Aucune réponse.</div>'}catch(x){l.innerHTML='<div class="empty-state">'+esc(x.message)+"</div>"}}
async function loadContacts(){const l=document.querySelector("#contact-list");try{const rows=await api("/api/admin/contacts");l.innerHTML=rows.map(x=>`<article class="admin-item contact-item" data-id="${x.id}"><div style="width:100%"><div class="contact-heading"><div><span class="ticket-status ${x.status==="answered"?"answered":"pending"}">${x.status==="answered"?"Répondu":"À traiter"}</span><h3>${esc(x.subject)}</h3><small>${esc(x.name)} · ${esc(x.email)} · ${new Date(x.updated_at||x.created_at).toLocaleString("fr-BE")}</small></div><button class="secondary-button open-thread" data-id="${x.id}">Voir la conversation</button></div><p>${esc(x.message)}</p><div class="thread-panel" hidden><div class="thread-messages"></div><textarea class="reply-box" rows="6" placeholder="Écrire votre réponse…"></textarea><div class="ticket-actions"><button class="primary-button send-reply" data-id="${x.id}">Envoyer la réponse</button><span class="form-status reply-status"></span></div></div></div></article>`).join("")||'<div class="empty-state">Aucune demande.</div>'}catch(x){l.innerHTML='<div class="empty-state">'+esc(x.message)+"</div>"}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function openThread(b){const p=b.closest(".contact-item").querySelector(".thread-panel");if(!p.hidden){p.hidden=true;b.textContent="Voir la conversation";return}b.disabled=true;try{const d=await api("/api/admin/contact-thread?id="+b.dataset.id);p.querySelector(".thread-messages").innerHTML=d.messages.map(m=>`<div style="padding:12px;margin:8px 0;border:1px solid #e4e7ec;border-radius:8px;background:${m.author_role==="admin"?"#f7f8ff":"#fff"}"><small>${m.author_role==="admin"?"Kelo Social":"Utilisateur"} · ${new Date(m.created_at).toLocaleString("fr-BE")}</small><p style="white-space:pre-wrap">${esc(m.message)}</p></div>`).join("");p.hidden=false;b.textContent="Masquer la conversation"}catch(x){alert(x.message)}finally{b.disabled=false}}
async function sendReply(b){const item=b.closest(".contact-item"),box=item.querySelector(".reply-box"),s=item.querySelector(".reply-status");if(!box.value.trim())return s.textContent="Écrivez une réponse.";b.disabled=true;s.textContent="Envoi…";try{await api("/api/admin/contact-reply",{method:"POST",body:JSON.stringify({id:b.dataset.id,message:box.value})});box.value="";s.textContent="Réponse envoyée. Le client continuera dans Kelo Social Help.";s.className="form-status success";await openThread(item.querySelector(".open-thread"));loadContacts()}catch(x){s.textContent=x.message;s.className="form-status error"}finally{b.disabled=false}}
document.addEventListener("click",e=>{const o=e.target.closest(".open-thread"),r=e.target.closest(".send-reply");if(o)openThread(o);if(r)sendReply(r)});check();