const loginCard=document.querySelector("#login-card"),dashboard=document.querySelector("#dashboard"),loginForm=document.querySelector("#login-form"),loginStatus=document.querySelector("#login-status"),logout=document.querySelector("#logout"),passwordInput=document.querySelector("#password"),togglePassword=document.querySelector("#toggle-password");
async function api(url,options={}){const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Erreur");return d;}
function showDashboard(){loginCard.hidden=true;dashboard.hidden=false;logout.hidden=false;loadKnowledge();}
async function check(){try{await api("/api/admin/session");showDashboard();}catch{}}
loginForm?.addEventListener("submit",async e=>{e.preventDefault();loginStatus.textContent="Vérification…";loginStatus.className="form-status";const button=loginForm.querySelector("button[type=submit]");button.disabled=true;try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:passwordInput.value})});loginForm.reset();showDashboard();}catch(err){loginStatus.textContent=err.message;loginStatus.className="form-status error";passwordInput.focus();passwordInput.select();}finally{button.disabled=false;}});
togglePassword?.addEventListener("click",()=>{const visible=passwordInput.type==="text";passwordInput.type=visible?"password":"text";togglePassword.textContent=visible?"Afficher":"Masquer";togglePassword.setAttribute("aria-label",visible?"Afficher le mot de passe":"Masquer le mot de passe");togglePassword.setAttribute("aria-pressed",String(!visible));});
logout?.addEventListener("click",async()=>{await api("/api/admin/logout",{method:"POST"}).catch(()=>{});location.reload();});
document.querySelectorAll(".admin-tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".admin-section").forEach(x=>x.hidden=x.id!==btn.dataset.tab);if(btn.dataset.tab==="contacts")loadContacts();}));
document.querySelector("#knowledge-form")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f).entries());b.published=f.published.checked;try{await api("/api/admin/knowledge",{method:"POST",body:JSON.stringify(b)});f.reset();f.published.checked=true;document.querySelector("#knowledge-status").textContent="Réponse ajoutée.";loadKnowledge();}catch(err){document.querySelector("#knowledge-status").textContent=err.message;}});
async function loadKnowledge(){const list=document.querySelector("#knowledge-list");try{const rows=await api("/api/admin/knowledge");list.innerHTML=rows.map(x=>`<article class="admin-item"><div><span class="ticket-status ${x.published?"answered":"closed"}">${x.published?"Active":"Désactivée"}</span><h3>${esc(x.title)}</h3><small>${esc(x.category||"Général")}</small><p>${esc(x.content)}</p></div><button class="text-button delete-knowledge" data-id="${x.id}">Supprimer</button></article>`).join("")||'<div class="empty-state">Aucune réponse enregistrée.</div>';list.querySelectorAll(".delete-knowledge").forEach(b=>b.onclick=async()=>{if(confirm("Supprimer cette réponse ?")){await api("/api/admin/knowledge",{method:"DELETE",body:JSON.stringify({id:b.dataset.id})});loadKnowledge();}});}catch(err){list.innerHTML='<div class="empty-state">'+esc(err.message)+'</div>';}}
async function loadContacts(){const list=document.querySelector("#contact-list");try{const rows=await api("/api/admin/contacts");list.innerHTML=rows.map(x=>`<article class="admin-item contact-item"><div><span class="ticket-status pending">Demande</span><h3>${esc(x.subject)}</h3><small>${esc(x.name)} · <a href="mailto:${esc(x.email)}">${esc(x.email)}</a> · ${new Date(x.created_at).toLocaleString("fr-BE")}</small><p>${esc(x.message)}</p><div class="reply-area"><textarea class="reply-box" rows="6" placeholder="Écrire votre réponse à ${esc(x.name)}…"></textarea><div class="ticket-actions"><button class="primary-button send-reply" data-email="${esc(x.email)}" data-subject="${esc(x.subject)}">Répondre par e-mail</button><span class="form-status reply-status"></span></div></div></div></article>`).join("")||'<div class="empty-state">Aucune demande.</div>';}catch(err){list.innerHTML='<div class="empty-state">'+esc(err.message)+'</div>';}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
check();
async function sendReply(button){const item=button.closest(".contact-item"),box=item.querySelector(".reply-box"),status=item.querySelector(".reply-status");if(!box.value.trim())return status.textContent="Écrivez une réponse avant l’envoi.";button.disabled=true;status.textContent="Envoi…";try{await api("/api/admin/contact-reply",{method:"POST",body:JSON.stringify({email:button.dataset.email,subject:button.dataset.subject,message:box.value})});box.value="";status.textContent="E-mail envoyé.";status.className="form-status success";}catch(err){status.textContent=err.message;status.className="form-status error";}finally{button.disabled=false;}}
document.addEventListener("click",e=>{const b=e.target.closest(".send-reply");if(b)sendReply(b);});