import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.95.0/+esm";
const supabase=createClient("https://fbtloeehynqobbwcndru.supabase.co","sb_publishable_O0bPmBKaynrYtSOwFybhhg_zZXTPCmZ");
const loginPanel=document.querySelector("#login-panel"),inbox=document.querySelector("#inbox"),list=document.querySelector("#ticket-list"),loginStatus=document.querySelector("#login-status"),logout=document.querySelector("#logout");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function load(){
 const {data:{user}}=await supabase.auth.getUser();
 if(!user){loginPanel.hidden=false;inbox.hidden=true;logout.hidden=true;return}
 const {data,error}=await supabase.from("help_tickets").select("*").order("created_at",{ascending:false});
 if(error){list.innerHTML='<div class="empty-state">Accès refusé ou impossible de charger les demandes.</div>';return}
 loginPanel.hidden=true;inbox.hidden=false;logout.hidden=false;
 list.innerHTML=data.length?data.map(t=>'<article class="ticket" data-id="'+esc(t.id)+'"><div class="ticket-top"><div><span class="ticket-status '+esc(t.status)+'">'+esc(t.status)+'</span><strong>'+esc(t.subject)+'</strong></div><time>'+new Date(t.created_at).toLocaleString("fr-BE")+'</time></div><div class="ticket-meta">'+esc(t.name)+' · <a href="mailto:'+esc(t.email)+'">'+esc(t.email)+'</a></div><p class="ticket-message">'+esc(t.message)+'</p><textarea class="reply-box" rows="4" placeholder="Préparez votre réponse…">'+esc(t.admin_reply||"")+'</textarea><div class="ticket-actions"><button class="secondary-button save-note">Enregistrer</button><a class="primary-button email-reply" href="mailto:'+encodeURIComponent(t.email)+'?subject='+encodeURIComponent("Re: "+t.subject)+'&body='+encodeURIComponent("Bonjour "+t.name+",\n\n")+'">Répondre par e-mail</a><select class="status-select"><option value="open" '+(t.status==="open"?"selected":"")+'>Ouverte</option><option value="pending" '+(t.status==="pending"?"selected":"")+'>En attente</option><option value="answered" '+(t.status==="answered"?"selected":"")+'>Répondue</option><option value="closed" '+(t.status==="closed"?"selected":"")+'>Fermée</option></select></div></article>').join(""):'<div class="empty-state">Aucune demande pour le moment.</div>';
 document.querySelectorAll(".ticket").forEach(card=>{const id=card.dataset.id;card.querySelector(".save-note").onclick=async()=>{const admin_reply=card.querySelector(".reply-box").value;const status=card.querySelector(".status-select").value;await supabase.from("help_tickets").update({admin_reply,status,replied_at:status==="answered"?new Date().toISOString():null,replied_by:user.id,updated_at:new Date().toISOString()}).eq("id",id);await load();};});
}
document.querySelector("#login-form")?.addEventListener("submit",async e=>{e.preventDefault();loginStatus.textContent="Connexion…";const {error}=await supabase.auth.signInWithPassword({email:document.querySelector("#admin-email").value,password:document.querySelector("#admin-password").value});loginStatus.textContent=error?"Connexion refusée. Vérifiez vos identifiants et vos droits administrateur.":"";if(!error)load()});
logout.onclick=async()=>{await supabase.auth.signOut();load()};document.querySelector("#refresh")?.addEventListener("click",load);load();