create extension if not exists pgcrypto;
create table if not exists public.help_admin_credentials(id bigint primary key generated always as identity,password_hash text not null,created_at timestamptz not null default now());
create table if not exists public.help_knowledge(id bigint primary key generated always as identity,title text not null,category text not null default 'Général',content text not null,published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.help_contacts(id bigint primary key generated always as identity,name text not null,email text not null,subject text not null,message text not null,access_token_hash text,access_token_encrypted text,status text not null default 'open' check(status in('open','answered','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.help_contact_messages(id bigint primary key generated always as identity,contact_id bigint not null references public.help_contacts(id) on delete cascade,author_role text not null check(author_role in('user','admin')),message text not null,created_at timestamptz not null default now());
alter table public.help_contacts add column if not exists access_token_hash text;
alter table public.help_contacts add column if not exists access_token_encrypted text;
alter table public.help_contacts add column if not exists status text;
alter table public.help_contacts add column if not exists updated_at timestamptz;
update public.help_contacts set status='open' where status is null;
update public.help_contacts set updated_at=created_at where updated_at is null;
alter table public.help_contacts alter column status set default 'open';
alter table public.help_contacts alter column updated_at set default now();
alter table public.help_admin_credentials enable row level security;
alter table public.help_knowledge enable row level security;
alter table public.help_contacts enable row level security;
alter table public.help_contact_messages enable row level security;
revoke all on table public.help_admin_credentials,public.help_knowledge,public.help_contacts,public.help_contact_messages from anon,authenticated;
grant all on table public.help_admin_credentials,public.help_knowledge,public.help_contacts,public.help_contact_messages to service_role;
create index if not exists help_contacts_token_idx on public.help_contacts(access_token_hash);
create index if not exists help_contact_messages_thread_idx on public.help_contact_messages(contact_id,created_at);
create or replace function public.verify_help_admin_password(candidate text) returns boolean language plpgsql security definer set search_path=public as $$declare stored_hash text;begin select password_hash into stored_hash from public.help_admin_credentials order by id desc limit 1;if stored_hash is null then return false;end if;return crypt(candidate,stored_hash)=stored_hash;end;$$;
revoke execute on function public.verify_help_admin_password(text) from public,anon,authenticated;
grant execute on function public.verify_help_admin_password(text) to service_role;